language: java
sudo: false
notifications:
  hipchat:
    rooms:
      secure: mDQq0lUZt98s168izAGCgBvCrtXYHjF7lk/8mcDmEtMUGJ+7mSm8SLvDiGvNca6gAst8iM098CCgNtIb/dOYIMQixWGhEC26EQ478/85d3PGjoo7+YdoJlFV4bnXzKvu4JMZxZ628lmWBW/PDlJn3/UxUJI22r6KDhgClYez8M2RT3XcAZEbUJLD2NsAN/T3yS5mBTg7EInMx8snepcJK1kpF1DdmH04JIVseJJ+T8SH1LlpY2jr7qHOViV7aQrefANeqMCEZ4LdoTrATaz8E+SZq76VS7SrBT6GLI1cgTVdh1KvRfuURAE1qwmYAivIkXg6Kvme4t3zzr/OjXRjT8GF5uFtLHFgSwGkD/yy6LE4pRTkLTrq5T5ouHbf8n+LIvq5a0JQqzaWcvO3fiKOBd7X67cHI3LTAJ+CKKbtVI5R9Pmt0iZ0dnnk7df/dcDDzkl5WSbpWxq4i9/m6cV+cDgqjw78fIGS9A5kDJ4bEfZpti+RiEQggoiNVrod5ihsgCNkQmWuj5rxTEjgyxbLKLFapOy0NxWUn0nPQMMbEc373SR72+gWA2tGxUtmNqGBaCunwaITRDYAlxr58u2zAD8Fz7ruGDml9/SJdopL1zbKd08SaOTUJJW5J49uUXnLLH77YHwcBjhslwX+eiYsBNWF88wkqOT3agNFDYYFESc=
